# example: <img class="doc-img-full" src="{{site.docs_img_dir}}PeopleCloud.png" alt="PeopleCloud" />
docs_dir: '/docs'
docs_img_dir: '/docs/img'
docs_pdf_dir: 'https://github.com/DataSketches/DataSketches.github.io/blob/master/docs/pdf'

core_api_snapshot: 'https://datasketches.github.io/api/core/snapshot/apidocs/index.html'
pig_api_snapshot: 'https://datasketches.github.io/api/pig/snapshot/apidocs/index.html'
hive_api_snapshot: 'https://datasketches.github.io/api/hive/snapshot/apidocs/index.html'
misc_api_snapshot: 'https://datasketches.github.io/api/misc/snapshot/apidocs/index.html'

core_readme: 'https://github.com/DataSketches/sketches-core/blob/master/README.md'
pig_readme: 'https://github.com/DataSketches/sketches-pig/blob/master/README.md'
hive_readme: 'https://github.com/DataSketches/sketches-hive/blob/master/README.md'

druid_datasketches: 'https://druid.apache.org/docs/latest/development/extensions-core/datasketches-extension.html'
